### PR TITLE
Fixes #1: Adds eof checking in `readOrThrow`.

### LINKED ISSUE #1: Parser ignores trailing parens.
The parser is ignoring trailing parens in expressions.

```
λ> (+ 1 3) (+ 1 2)
3
λ> (+ 1 3) (+ 1 2))))
3
```

### PR DESCRIPTION
**Pull request by zfnmxt**
Not sure if this is what you had in mind.

Also, your parser is pretty whitespace intolerant (i.e. `(+ 1 3)  ` is rejected). Is that by design?

I also took the liberty to clean up some trailing whitespace and whatnot.

### CODE REVIEW

**Comment by 0x0f0f0f** [comment]
It's the first parser I write so it's still quite rough. Did you use any tool to clean whitespace?
What do you suggest to do for a better handling of whitespace?

**Comment by zfnmxt** [comment]
I just used Emac's `whitespace-cleanup` function. But there are also nice Haskell-specific tools like https://github.com/jaspervdj/stylish-haskell

As for whitespace in the parser, I think it's nice with parser combinators to make a sort of "tokenizer" function that basically wraps a given parser `p :: Parser a` to also eat up any preceding (or trailing, your choice) whitespace. 

Something like:

```hs
tokenize :: Parser a -> Parser a
tokenize = (whitespace >>)
```

Then you can tokenize your "primitive" parsers and have better whitespace handling. The issue I pointed out above would then be solved by calling `tokenize eof` instead of `eof`. (And you shouldn't have a thousand `tokenize` calls in your code--you only need them to preceed "primitive" parsers, generally, and you can wrap oft-called functions, e.g. `charT = tokenize char`.)

**Comment by 0x0f0f0f** [comment]
```
λ> (load "stdlib/stdlib.scm")
Parse error at "lisp" (line 105, column 1):
unexpected end of input
expecting ";", digit, "#d", "#b", "#o", "#x", letter, "\"", "#", "#\\", "'", "`", "#(" or "("
```

Now errors when loading files. Errors at last (empty) line.

https://github.com/0x0f0f0f/yasih/blob/master/src/LispParser.hs#L30-L31

**Comment by zfnmxt** [comment]
The error occurs due to some iffy whitespace stuff, and due to an error in your definition of `parseComment` (you should replace the `eof` parser with something else there):

https://github.com/0x0f0f0f/yasih/blob/08259fc81684aa1e01e33c93108a35ee58c59b07/src/LispParser.hs#L293-L296

I'd also recommend that you get rid of the `sepEndBy` call in `readExprList` (and replace it with `many` or `many1` depending on your preferences) and, in fact, do no whitespace handling in that function at all. It's actually totally unnecessary since `mainParser` already eats whitespace before and (unnecessarily) after:

https://github.com/0x0f0f0f/yasih/blob/08259fc81684aa1e01e33c93108a35ee58c59b07/src/LispParser.hs#L30-L32

I'm happy to submit a PR with fixes if you want, or try and figure it out for yourself. :)

**Comment by 0x0f0f0f** [comment]
Thanks! Fixed. It may need cleanup but now it's working correctly :)
The only remaining problem is that now single line comments in the REPL are not parsed correctly because they expect a newline but actually receive EOF
https://github.com/0x0f0f0f/yasih/commit/51cb4d5d40dd85661be26f07c46900d2dbba0ef7

**Comment by zfnmxt** [comment]
Aha, didn't think about that. Alright, unless you want to do some annoying checking in the comments parser and `readOrThrow`, the solution is to get rid of the `eof` check in `readOrThrow`.

Instead, we can just directly check the parser monad for remaining input. Something like this:

```hs
readOrThrow :: Parser a -> String -> ThrowsError a
readOrThrow parser input =
    let checkEmpty = do
          rest <- getInput
          unless (null rest) $ fail $ "Non-empty: " ++ rest
        parser' = parser <* checkEmpty in
    case parse parser' "lisp" input of
    Left err -> throwError $ Parser err
    Right val -> return val
```

I haven't tested it, but I think that should fix the issue (without causing new ones...hopefully!)

**Comment by 0x0f0f0f** [comment]
It works! I've done some changes to the REPL too so that empty lines and comment-only lines are ignored. https://github.com/0x0f0f0f/yasih/blob/48dd1f4d3cf1117c763fcecac3ddec78ade7575c/src/LispRepl.hs#L36-L48

The parser still needs a lot of fixes and maybe using GenTokenParser would solve a lot of those problems. for example, a comment inside a multiline function in a file still errors.
What do you recommend?

**Comment by zfnmxt** [comment]
Using `GenTokenParser` is certainly an option--depends how interested you are in defining the parsers yourself or not.

Otherwise, I recommend you start with the `tokenize` approach I mentioned above. Try to minimize your number of `whitespace` calls and whatnot. Also, I recommend not treating comments differently from "normal" whitespace: it's all whitespace. Your whitespace parser should handle all of it (and the only thing that calls `parseComment` should be your whitespace parser).

Once your whitespace consumption becomes a bit more disciplined/structured, it should be easy to iron out any lasting bugs.

Also I'm a bit suspicious of having a special case for comment-only lines (i.e., whitespace-only lines) for your REPL. Your parser can handle this successfully in general (you may need `many` where you currently have `many1`) and would just return an empty (but successful) parse. I wouldn't special case it--then you're doing parsing work in your REPL logic, where you should only be parsing in your parser!

**Comment by 0x0f0f0f** [comment]
How should I return an empty parse? Would you use a Maybe monad?

**Comment by zfnmxt** [comment]
I'd change `many1` to `many`:

https://github.com/0x0f0f0f/yasih/blob/48dd1f4d3cf1117c763fcecac3ddec78ade7575c/src/LispParser.hs#L33-L35

An empty parse then just yields an empty list of type `LispVal`, i.e., the empty program.

**Pull request merged**
